apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: dev
  labels:
    app: mysqlapp
spec:
  ports:
    - port: 3306
  selector:
    app: mysqlapp
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: dev
  labels:
    app: mysqlapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-dep
  namespace: dev
  labels:
    app: mysqlapp
spec:
  selector:
    matchLabels:
      app: mysqlapp
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqlapp
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        env:
        - name: MYSQL_ROOT_PASSWORD # Setting Database Name from a 'Secret'
          #value: root
          valueFrom:
            secretKeyRef:
              name: users-secrets
              key: "db.password"
        - name: MYSQL_DATABASE # Setting Database Name from a 'ConfigMap'
          #value: testdb
          valueFrom:
            configMapKeyRef:
              name: users-config
              key: "db.name"
        livenessProbe:
          tcpSocket:
            port: 3306
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim